---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)

date <- "11/12/2020"

quarter <- "Fall2020"
date <- "11/12"
week_folder <- "11-12_Luetgert"


title <- "Clustering Countries-Improving Measurement in Comparative Political Research"


speaker <- "Brooke Luetgert"
department <- "Research and Computing Center"
university <- "University of Chicago"
github_home <- "https://github.com/uchicago-computation-workshop"

#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Fall2020/issues/8"
zoom_url <- "https://uchicago.zoom.us/meeting/register/tJ0kduyqpjMuGtz03nDK2KMi39ig-QF3iQr9"


#Papers

week_paper_ref0 <- "" 
week_paper_file0 <- "" 



#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")



```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** Global development indicators are widely used to estimate the macroeconomic and institutional stability of a country. However, as the number of different indicators continues to expand, it has become difficult to interpret this high dimensional data as a whole. Identifying overall trends and assessing how indicators are related to each other can be further obscured by qualitative indices of broad concepts such as democratic stability. While these data continue to increase in dimensionality, empirical research often struggles to explain complex and nuanced societal change from a comparative perspective. Classic approaches to comparative democratic research frequently opt for additive indices like Polity IV, or level measures such as GDP; however, individual indicators often suffer from limited temporal variance. As social scientists, our theoretical work is more advanced than our indicators. The goal of this study is to better understand how we can measure variation across countries with regard to their social and economic division. Employing dimension reduction and subsequent clustering to the vast pool of indicators currently available, the aim is to derive a richer means of describing countries in their development over time. The implications of this explorative, data driven approach are promising: As we better understand the underlying structure of our country level data, we move toward building more effective, objective socio- economic measures and even predictive social science research.

</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:20am-12:40pm </h4>

<br><br>

<p class=footertext2>

**Brooke Luetgert** is a Computational Scientist for the Social Sciences Division and Lecturer in the Digital Studies program at the University of Chicago. Prior to joining the RCC, she was an Assistant Professor of Political Science and Research Methodology at Sabanci University in Istanbul, Turkey. She has several distinguished publications on legislative compliance, European Union politics and public opinion formation. Her work on mixing methodological approaches to measure EU compliance received post- doctoral funding through the EU CORDIS Marie Curie program as well as a generous grant from Land Baden-Württemburg, Germany. Her current work employs machine learning and interactive data visualization to identify democratic backsliding and fractionalization in a comparative perspective. Brooke lives on a farm with her husband, three amazing kids and menagerie. Together, they also run a thriving children’s center for competitive robotics and computer coding in Batavia, IL.

</p>

<br>

<p class=footertext2>

**Registration**: The presentation will be held virtually on Zoom. For security purposes, please register through this [link](`r zoom_url`) to request access. Only accounts affiliated with the University of Chicago will be granted access.
</p>

This week's suggested readings:

- `r readings0`


<br>

<br><br>


---

<p class=footertext> The 2020-2021 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11:20 a.m. to 12:40 p.m.. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>