---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)

date <- "11/19/2020"

quarter <- "Fall2020"
date <- "11/19"
week_folder <- "11-19_Waggoner"


title <- "Pandemic Policymaking"


speaker <- "Philip Waggoner"
department <- "Computational Social Science"
university <- "University of Chicago"
github_home <- "https://github.com/uchicago-computation-workshop"

#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Fall2020/issues/9"
zoom_url <- "https://uchicago.zoom.us/meeting/register/tJIpc-GsqTooGdUVM-OJcsnUQIWQxu1jUQJG"


#Papers

week_paper_ref0 <- "Waggoner, 2020. 'Pandemic Policymaking: Learning the Lower Dimensional Manifold of Congressional Responsiveness'"
week_paper_file0 <- "waggoner_pandemic.pdf"

week_paper_ref1 <- "Waggoner, 2020. 'A Computational Exploration of the Evolution of Governmental Policy Responses to Epidemics Before and During the Era of COIVD-19'" 
week_paper_file1 <- "waggoner_final_CCSE_manuscript.pdf"



#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")

readings1 <- paste0("[", week_paper_ref1,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file1,")")


```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** Are we witnessing a unique period of Congressional policymaking, or is this era of policymaking in response to COVID-19 in line with the current hyperpolarization, political division, and ineffective governance that defines much of policymaking? To answer this question, we need to place COVID-19 policymaking into historical context. In this talk, I develop an exploratory framework based on a suite of computational methods and an original dataset of text and non-text data on all epidemic- and pandemic-related legislation from 1973 - 2020. Results suggest that though institutional patterns of policymaking are strikingly uniform overtime (suggesting we are not in a unique period of policymaking), the overall tone of the policymaking apparatus in this space has become increasingly intense, and overtly negative in the current era (suggesting we are in a unique period of policymaking). In sum, and to make sense of these patterns, this suggests a few things: first, "uniqueness" is a multidimensional concept that must be treated accordingly; second, though somewhat hopeful to observe uniformity in the institutional procedure for formally responding to such large-scale crises, the process for deriving governmental responses is becoming increasingly, and perhaps unnecessarily, intense and negative; and finally, dependent on where we look for evidence will determine whether and what we find. For example, we find evidence of uniqueness in the "how" of policymaking when looking to bill text, yet we find no evidence of uniqueness when we look to the institutional contours that defined paths policies take in the chamber. As a result, several avenues open up for future related work.

</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:20am-12:40pm </h4>

<br><br>

<p class=footertext2>

**Philip Waggoner** is an Assistant Instructional Professor in the Masters in the Computational Social Science program and a political scientist applying experimental, statistical, and computational techniques to explore a variety of social science behavior. His research has appeared in numerous political science, statistics, and software outlets, and has received generous financial support from several funders. His teaching interests include American political decision- making, machine learning, applied statistics, and statistical computing. He earned his PhD in political science from the University of Houston.

</p>

<br>

<p class=footertext2>

**Registration**: The presentation will be held virtually on Zoom. For security purposes, please register through this [link](`r zoom_url`) to request access. Only accounts affiliated with the University of Chicago will be granted access.
</p>

This week's suggested readings:

- `r readings0`
- `r readings1`

<br>

<br><br>


---

<p class=footertext> The 2020-2021 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11:20 a.m. to 12:40 p.m.. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>