---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)

date <- "10/29/2020"

quarter <- "Fall2020"
date <- "10/29"
week_folder <- "10-29_Ellison"


title <- "Why We Don't Click: Interrogating the Relationship Between Viewing and Clicking in Social Media Contexts by Exploring the 'Non-Click'"


speaker <- "Nicole B. Ellison"
department <- "School of Information"
university <- "University of Michigan"
github_home <- "https://github.com/uchicago-computation-workshop"

#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Fall2020/issues/6"
zoom_url <- "https://uchicago.zoom.us/meeting/register/tJAkfuyhpzsuGtRDQfQs868j_o2tO2vBOKuk"


#Papers

week_paper_ref0 <- "Ellison, Trieu, Schoenebeck, Brewer, & Israni 2020. 'Why We Don't Click: Interrogating the Relationship Between Viewing and Clicking in Social Media Contexts by Exploring the 'Non-Click''"
week_paper_file0 <- "ellison_2020.pdf"



#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")



```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** Motivated by work that characterizes view-based social media practices as “passive use,” contrasting it with more desirable, interactive “active use,” this study explores how social media users understand their viewing and clicking practices and the empirical relationship between them. Employing a combination of eye tracking, survey, and interview methods, our study (N = 42) investigates the non-click—instances where people intentionally and thoughtfully do not click on content they spend time viewing. Counterintuitively, we find no difference in viewing duration to clicked versus non-clicked Facebook content. We find that use motivations and Facebook feed content are significant predictors of click behavior but measures of overall use, such as network size or minutes of use per day, are not. Our interview data reveal three audience-related concerns that contribute to deliberate non-clicking and illustrate how non-clicked content contributes to social connectedness when imported into other channels. We discuss implications for researchers, users, and designers.

</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:20am-12:40pm </h4>

<br><br>

<p class=footertext2>

**Nicole B. Ellison** is the Karl E. Weick Collegiate Professor of Information in the School of Information at the University of Michigan.  Nicole's research has explored social and interpersonal aspects of online technologies and computer-mediated communication, including research on self-presentational strategies used by online dating participants; the role of social media in reshaping college access patterns for low-income and first-generation college students; and the ways in which users employ the communication affordances of Facebook to receive and give social and informational support to members of their network. This research has been funded by the National Science Foundation, the Bill & Melinda Gates Foundation, and the National Academies of Science. 
</p>

<br>

<p class=footertext2>

**Registration**: The presentation will be held virtually on Zoom. For security purposes, please register through this [link](`r zoom_url`) to request access. Only accounts affiliated with the University of Chicago will be granted access.
</p>

This week's suggested readings:

- `r readings0`


<br>

<br><br>

---

<p class=footertext> The 2020-2021 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11:20 a.m. to 12:40 p.m.. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>